- [Blog Link](http://datapigtechnologies.com/blog/index.php/highlighting-outliers-in-your-data-with-the-tukey-method/)

- There are lots of statistical methods for identifying outliers. This noteboik uses John Tukey’s method of leveraging the Interquartile Range. His method is applicable to most ranges since it isn’t dependent on distributional assumptions. It also ignores the mean and standard deviation, making it resistant to being influenced by the extreme values in the range.

In [1]:
import pandas as pd

df = pd.read_csv("sysco.csv")

df.head()

   Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
0  12669  9656     7561     214              2674          1338
1   7057  9810     9568    1762              3293          1776
2   6353  8808     7684    2405              3516          7844
3  13265  1196     4221    6404               507          1788
4  22615  5410     7198    3915              1777          5185

In [2]:
import numpy as np
from IPython.display import display # Allows the use of display() for DataFrames

### = Find Outliers For Each Feature...
Displays a DataFrame for each feature made up of only the rows that have outliers for that feature

In [3]:
# Keep outlier indices in a list and examine after looping thru the features
idx = []

# For each feature find the data points with extreme high or low values
for feature in df.keys():

    # DONE: Calculate Q1 (25th percentile of the data) for the given feature
    Q1 = np.percentile(df[feature], 25)

    # DONE: Calculate Q3 (75th percentile of the data) for the given feature
    Q3 = np.percentile(df[feature], 75)

    # TODO: Use the interquartile range to calculate an outlier step (1.5 times the interquartile range)
    iqr = Q3 - Q1
    step = iqr*1.5

    # Displays a DataFrame for each feature made up of only the rows that have outliers for that feature
    print("Data points considered outliers for the feature '{}':".format(feature))
    display(df[~((df[feature] >= Q1 - step) & (df[feature] <= Q3 + step))])

    # Adds the indexes of all the outliers to our empty idx log list
    idx += df[~((df[feature] >= Q1 - step) & (df[feature] <= Q3 + step))].index.tolist()
    print(idx)

Data points considered outliers for the feature 'Fresh':

      Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
29    43088   2100     2609    1200              1107           823
39    56159    555      902   10002               212          2916
47    44466  54259    55571    7782             24171          6465
52    40721   3916     5876     532              2587          1278
87    43265   5025     8117    6312              1579         14351
103   56082   3504     8906   18028              1480          2498
125   76237   3473     7102   16538               778           918
129   42312    926     1510    1718               410          1819
176   45640   6958     6536    7368              1532           230
181  112151  29627    18148   16745              4948          8550
239   47493   2567     3779    5243               828          2253
258   56083   4563     2124    6422               730          3321
259   53205   4959     7336    3012               967           818
282   49063   3965     4252    5970              1041          1404
284   68951   4411    12609    8692               751          2406
285   40254    640     3600    1042               436            18
289   42786    286      471    1388                32            22
370   39679   3944     4955    1364               523          2235
377   38793   3154     2648    1034                96          1242
436   39228   1431      764    4510                93          2346

[29, 39, 47, 52, 87, 103, 125, 129, 176, 181, 239, 258, 259, 282, 284, 285, 289, 370, 377, 436]
Data points considered outliers for the feature 'Milk':

      Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
23    26373  36423    22019    5154              4337         16523
28     4113  20484    25957    1158              8604          5206
38     4591  15729    16709      33              6956           433
45     5181  22044    21531    1740              7353          4985
47    44466  54259    55571    7782             24171          6465
49     4967  21412    28921    1798             13583          1163
56     4098  29892    26866    2616             17740          1340
61    35942  38369    59598    3254             26701          2017
65       85  20959    45828      36             24231          1423
85    16117  46197    92780    1026             40827          2944
86    22925  73498    32114     987             20070           903
92     9198  27472    32034    3232             18906          5130
109    1406  16729    28986     673               836             3
163    5531  15726    26870    2367             13726           446
171     200  25862    19816     651              8773          6250
181  112151  29627    18148   16745              4948          8550
183   36847  43950    20170   36534               239         47943
211   12119  28326    39694    4736             19410          2870
216    2532  16599    36486     179             13308           674
251    6134  23133    33586    6746             18594          5121
254   10379  17972     4748    4686              1547          3265
265    5909  23527    13699   10155               830          3636
309     918  20655    13567    1465              6846           806
319    9759  25071    17645    1128             12408          1625
325   32717  16784    13626   60869              1272          5609
358     759  18664     1660    6114               536          4100
384   10683  21858    15400    3635               282          5120
427   31012  16687     5429   15082               439          1163

[29, 39, 47, 52, 87, 103, 125, 129, 176, 181, 239, 258, 259, 282, 284, 285, 289, 370, 377, 436, 23, 28, 38, 45, 47, 49, 56, 61, 65, 85, 86, 92, 109, 163, 171, 181, 183, 211, 216, 251, 254, 265, 309, 319, 325, 358, 384, 427]
Data points considered outliers for the feature 'Grocery':

     Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
28    4113  20484    25957    1158              8604          5206
43     630  11095    23998     787              9529            72
47   44466  54259    55571    7782             24171          6465
49    4967  21412    28921    1798             13583          1163
56    4098  29892    26866    2616             17740          1340
61   35942  38369    59598    3254             26701          2017
65      85  20959    45828      36             24231          1423
77   12205  12697    28540     869             12034          1009
85   16117  46197    92780    1026             40827          2944
86   22925  73498    32114     987             20070           903
92    9198  27472    32034    3232             18906          5130
109   1406  16729    28986     673               836             3
145  22039   8384    34792      42             12591          4430
163   5531  15726    26870    2367             13726           446
201   4484  14399    24708    3549             14235          1681
205   1107  11711    23596     955              9265           710
211  12119  28326    39694    4736             19410          2870
216   2532  16599    36486     179             13308           674
251   6134  23133    33586    6746             18594          5121
304    161   7460    24773     617             11783          2410
331  11223  14881    26839    1234              9606          1102
333   8565   4980    67298     131             38102          1215
343   1689   6964    26316    1456             15469            37
437  14531  15488    30243     437             14841          1867

[29, 39, 47, 52, 87, 103, 125, 129, 176, 181, 239, 258, 259, 282, 284, 285, 289, 370, 377, 436, 23, 28, 38, 45, 47, 49, 56, 61, 65, 85, 86, 92, 109, 163, 171, 181, 183, 211, 216, 251, 254, 265, 309, 319, 325, 358, 384, 427, 28, 43, 47, 49, 56, 61, 65, 77, 85, 86, 92, 109, 145, 163, 201, 205, 211, 216, 251, 304, 331, 333, 343, 437]
Data points considered outliers for the feature 'Frozen':

      Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
22    31276   1917     4469    9408              2381          4334
39    56159    555      902   10002               212          2916
40    24025   4332     4757    9510              1145          5864
47    44466  54259    55571    7782             24171          6465
70    16705   2037     3202   10643               116          1365
72     4420   5139     2661    8872              1321           181
73    19899   5332     8713    8132               764           648
88     7864    542     4042    9735               165            46
91    12754   2762     2530    8693               627          1117
93    11314   3090     2062   35009                71          2698
103   56082   3504     8906   18028              1480          2498
112   19046   2770     2469    8853               483          2708
125   76237   3473     7102   16538               778           918
126   19219   1840     1658    8195               349           483
143   10405   1596     1096    8425               399           318
181  112151  29627    18148   16745              4948          8550
183   36847  43950    20170   36534               239         47943
195   17023   5139     5230    7888               330          1755
196   30624   7209     4897   18711               763          2876
230   11072   5989     5615    8321               955          2137
240   22096   3575     7041   11422               343          2564
265    5909  23527    13699   10155               830          3636
277    9061    829      683   16919               621           139
283   25767   3613     2013   10303               314          1384
284   68951   4411    12609    8692               751          2406
287   15354   2102     2828    8366               386          1027
310    7034   1492     2405   12569               299          1117
325   32717  16784    13626   60869              1272          5609
328   16933   2209     3389    7849               210          1534
334   16823    928     2743   11559               332          3486
337    9351   1347     2611    8170               442           868
338       3    333     7021   15601                15           550
339    2617   1188     5332    9584               573          1942
371   20105   1887     1939    8164               716           790
381   17770   4591     1617    9927               246           532
393   23632   6730     3842    8620               385           819
401   27167   2801     2128   13223                92          1902
406   25066   5010     5026    9806              1092           960
413    4983   4859     6633   17866               912          2435
425   11243   2408     2593   15348               108          1886
427   31012  16687     5429   15082               439          1163
431    8533   5506     5160   13486              1377          1498
435   29703  12051    16027   13135               182          2204

[29, 39, 47, 52, 87, 103, 125, 129, 176, 181, 239, 258, 259, 282, 284, 285, 289, 370, 377, 436, 23, 28, 38, 45, 47, 49, 56, 61, 65, 85, 86, 92, 109, 163, 171, 181, 183, 211, 216, 251, 254, 265, 309, 319, 325, 358, 384, 427, 28, 43, 47, 49, 56, 61, 65, 77, 85, 86, 92, 109, 145, 163, 201, 205, 211, 216, 251, 304, 331, 333, 343, 437, 22, 39, 40, 47, 70, 72, 73, 88, 91, 93, 103, 112, 125, 126, 143, 181, 183, 195, 196, 230, 240, 265, 277, 283, 284, 287, 310, 325, 328, 334, 337, 338, 339, 371, 381, 393, 401, 406, 413, 425, 427, 431, 435]
Data points considered outliers for the feature 'Detergents_Paper':

     Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
43     630  11095    23998     787              9529            72
47   44466  54259    55571    7782             24171          6465
49    4967  21412    28921    1798             13583          1163
56    4098  29892    26866    2616             17740          1340
61   35942  38369    59598    3254             26701          2017
65      85  20959    45828      36             24231          1423
77   12205  12697    28540     869             12034          1009
85   16117  46197    92780    1026             40827          2944
86   22925  73498    32114     987             20070           903
92    9198  27472    32034    3232             18906          5130
145  22039   8384    34792      42             12591          4430
155   1989  10690    19460     233             11577          2153
163   5531  15726    26870    2367             13726           446
173    514   7677    19805     937              9836           716
200   3067  13240    23127    3941              9959           731
201   4484  14399    24708    3549             14235          1681
209   5550  12729    16767     864             12420           797
211  12119  28326    39694    4736             19410          2870
216   2532  16599    36486     179             13308           674
251   6134  23133    33586    6746             18594          5121
303   2599   3688    13829     492             10069            59
304    161   7460    24773     617             11783          2410
312   2137   3737    19172    1274             17120           142
319   9759  25071    17645    1128             12408          1625
331  11223  14881    26839    1234              9606          1102
333   8565   4980    67298     131             38102          1215
343   1689   6964    26316    1456             15469            37
349   5981  14641    20521    2005             12218           445
351   1210  10044    22294    1741             12638          3137
437  14531  15488    30243     437             14841          1867

[29, 39, 47, 52, 87, 103, 125, 129, 176, 181, 239, 258, 259, 282, 284, 285, 289, 370, 377, 436, 23, 28, 38, 45, 47, 49, 56, 61, 65, 85, 86, 92, 109, 163, 171, 181, 183, 211, 216, 251, 254, 265, 309, 319, 325, 358, 384, 427, 28, 43, 47, 49, 56, 61, 65, 77, 85, 86, 92, 109, 145, 163, 201, 205, 211, 216, 251, 304, 331, 333, 343, 437, 22, 39, 40, 47, 70, 72, 73, 88, 91, 93, 103, 112, 125, 126, 143, 181, 183, 195, 196, 230, 240, 265, 277, 283, 284, 287, 310, 325, 328, 334, 337, 338, 339, 371, 381, 393, 401, 406, 413, 425, 427, 431, 435, 43, 47, 49, 56, 61, 65, 77, 85, 86, 92, 145, 155, 163, 173, 200, 201, 209, 211, 216, 251, 303, 304, 312, 319, 331, 333, 343, 349, 351, 437]
Data points considered outliers for the feature 'Delicatessen':

      Fresh   Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
2      6353   8808     7684    2405              3516          7844
4     22615   5410     7198    3915              1777          5185
17     5876   6157     2933     839               370          4478
22    31276   1917     4469    9408              2381          4334
23    26373  36423    22019    5154              4337         16523
24    22647   9776    13792    2915              4482          5778
28     4113  20484    25957    1158              8604          5206
36    29955   4362     5428    1729               862          4626
40    24025   4332     4757    9510              1145          5864
45     5181  22044    21531    1740              7353          4985
47    44466  54259    55571    7782             24171          6465
71    18291   1266    21042    5373              4173         14472
87    43265   5025     8117    6312              1579         14351
92     9198  27472    32034    3232             18906          5130
145   22039   8384    34792      42             12591          4430
171     200  25862    19816     651              8773          6250
181  112151  29627    18148   16745              4948          8550
183   36847  43950    20170   36534               239         47943
202   25203  11487     9490    5065               284          6854
218      18   7504    15205    1285              4797          6372
251    6134  23133    33586    6746             18594          5121
325   32717  16784    13626   60869              1272          5609
358     759  18664     1660    6114               536          4100
372    3884   3801     1641     876               397          4829
384   10683  21858    15400    3635               282          5120
409    8708   3634     6100    2349              2123          5137
411    2126   3289     3281    1535               235          4365

[29, 39, 47, 52, 87, 103, 125, 129, 176, 181, 239, 258, 259, 282, 284, 285, 289, 370, 377, 436, 23, 28, 38, 45, 47, 49, 56, 61, 65, 85, 86, 92, 109, 163, 171, 181, 183, 211, 216, 251, 254, 265, 309, 319, 325, 358, 384, 427, 28, 43, 47, 49, 56, 61, 65, 77, 85, 86, 92, 109, 145, 163, 201, 205, 211, 216, 251, 304, 331, 333, 343, 437, 22, 39, 40, 47, 70, 72, 73, 88, 91, 93, 103, 112, 125, 126, 143, 181, 183, 195, 196, 230, 240, 265, 277, 283, 284, 287, 310, 325, 328, 334, 337, 338, 339, 371, 381, 393, 401, 406, 413, 425, 427, 431, 435, 43, 47, 49, 56, 61, 65, 77, 85, 86, 92, 145, 155, 163, 173, 200, 201, 209, 211, 216, 251, 303, 304, 312, 319, 331, 333, 343, 349, 351, 437, 2, 4, 17, 22, 23, 24, 28, 36, 40, 45, 47, 71, 87, 92, 145, 171, 181, 183, 202, 218, 251, 325, 358, 372, 384, 409, 411]

### = List of all Outlier Indexs...

In [4]:
# Look at a sorted list of all combine feature outlier indices
print(sorted(idx))

[2, 4, 17, 22, 22, 23, 23, 24, 28, 28, 28, 29, 36, 38, 39, 39, 40, 40, 43, 43, 45, 45, 47, 47, 47, 47, 47, 47, 49, 49, 49, 52, 56, 56, 56, 61, 61, 61, 65, 65, 65, 70, 71, 72, 73, 77, 77, 85, 85, 85, 86, 86, 86, 87, 87, 88, 91, 92, 92, 92, 92, 93, 103, 103, 109, 109, 112, 125, 125, 126, 129, 143, 145, 145, 145, 155, 163, 163, 163, 171, 171, 173, 176, 181, 181, 181, 181, 183, 183, 183, 195, 196, 200, 201, 201, 202, 205, 209, 211, 211, 211, 216, 216, 216, 218, 230, 239, 240, 251, 251, 251, 251, 254, 258, 259, 265, 265, 277, 282, 283, 284, 284, 285, 287, 289, 303, 304, 304, 309, 310, 312, 319, 319, 325, 325, 325, 328, 331, 331, 333, 333, 334, 337, 338, 339, 343, 343, 349, 351, 358, 358, 370, 371, 372, 377, 381, 384, 384, 393, 401, 406, 409, 411, 413, 425, 427, 427, 431, 435, 436, 437, 437]

In [5]:
import collections

# Find any outliers occurring more than once
counts = collections.Counter(idx)
print(counts)

Counter({47: 6, 92: 4, 181: 4, 251: 4, 28: 3, 49: 3, 56: 3, 61: 3, 65: 3, 85: 3, 86: 3, 145: 3, 163: 3, 183: 3, 211: 3, 216: 3, 325: 3, 22: 2, 23: 2, 39: 2, 40: 2, 43: 2, 45: 2, 77: 2, 87: 2, 103: 2, 109: 2, 125: 2, 171: 2, 201: 2, 265: 2, 284: 2, 304: 2, 319: 2, 331: 2, 333: 2, 343: 2, 358: 2, 384: 2, 427: 2, 437: 2, 2: 1, 4: 1, 17: 1, 24: 1, 29: 1, 36: 1, 38: 1, 52: 1, 70: 1, 71: 1, 72: 1, 73: 1, 88: 1, 91: 1, 93: 1, 112: 1, 126: 1, 129: 1, 143: 1, 155: 1, 173: 1, 176: 1, 195: 1, 196: 1, 200: 1, 202: 1, 205: 1, 209: 1, 218: 1, 230: 1, 239: 1, 240: 1, 254: 1, 258: 1, 259: 1, 277: 1, 282: 1, 283: 1, 285: 1, 287: 1, 289: 1, 303: 1, 309: 1, 310: 1, 312: 1, 328: 1, 334: 1, 337: 1, 338: 1, 339: 1, 349: 1, 351: 1, 370: 1, 371: 1, 372: 1, 377: 1, 381: 1, 393: 1, 401: 1, 406: 1, 409: 1, 411: 1, 413: 1, 425: 1, 431: 1, 435: 1, 436: 1})

In [6]:
# Make a final list of indicies with no duplicates
outliers = []
outliers = [item for item, count in collections.Counter(idx).items() if count > 1]
print(outliers)

[22, 23, 28, 39, 40, 43, 45, 47, 49, 56, 61, 65, 77, 85, 86, 87, 92, 103, 109, 125, 145, 163, 171, 181, 183, 201, 211, 216, 251, 265, 284, 304, 319, 325, 331, 333, 343, 358, 384, 427, 437]

### = Make a New Dataframe With Outliers Removed...

In [15]:
good_data = df.drop(df.index[outliers]).reset_index(drop = True)
good_data.head()

   Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicatessen
0  12669  9656     7561     214              2674          1338
1   7057  9810     9568    1762              3293          1776
2   6353  8808     7684    2405              3516          7844
3  13265  1196     4221    6404               507          1788
4  22615  5410     7198    3915              1777          5185